winget install -e --id Spotify.Spotify
winget install -e --id Notepad++.Notepad++
winget install -e --id Python.Python.3.14
winget install -e --id Happ.Happ
winget install -e --id Telegram.TelegramDesktop
winget install -e --id Discord.Discord
winget install -e --id Hibbiki.Chromium
winget install -e --id Microsoft.DotNet.Runtime.10
winget install -e --id Microsoft.VCRedist.2015+.x86
winget install -e --id mpv.net
winget install -e --id qBittorrent.qBittorrent
winget install -e --id REALiX.HWiNFO
winget install -e --id LocalSend.LocalSend
winget install -e --id FilesCommunity.Files
winget install -e --id Klocman.BulkCrapUninstaller
winget install -e --id PrismLauncher.PrismLauncher
winget install -e --id Valve.Steam
winget install -e --id Roblox.Roblox  
winget install -e --id Joplin.Joplin
winget install -e --id Google.GoogleDrive
